apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
      app.kubernetes.io/name: db
      app.kubernetes.io/instance: db
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: customers
      app.kubernetes.io/managed-by: helm
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/name: db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
      app.kubernetes.io/name: db
      app.kubernetes.io/instance: db
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: microservice
      app.kubernetes.io/part-of: customers
      app.kubernetes.io/managed-by: helm  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
    spec:
      containers:
        - image: mysql:5.7
          name: db       
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi #256Mi
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: db01
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: db_user           
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: db_pwd                          
          volumeMounts:
          - name: mysql-data
            mountPath: "/var/lib/mysql"
            subPath: "mysql"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pv-claim        
